version: '3.9'

services:
  portal:
    environment:
      - NODE_ENV=development
      - DEBUG=*
    ports:
      - "3000:3000"
      - "5173:5173"  # Vite hot module replacement
    volumes:
      - ../../frontend:/app/frontend
      - /app/node_modules  # Prevent overwrite of node_modules
    command: npm run dev
    stdin_open: true
    tty: true
